### ISSUE TITLE
(MAINTENANCE) poprawki przypisań do profili firm

### ISSUE THREAD

**Issue by KarolinaTEH** [ecommerceberlin/targiehandlu.pl#119]
było (ID) -> TEH23 (ID)

czechlogistic.pl 1164 ->	paxy.pl 2239
nowekolory.pl  1869 ->	magicapp.pl 2241
smsapi.pl 1232 ->	linkmobility.com 2014
goglobal24.com 1202 -> global24.com 2240
brandation.pl 1855 -> mbank.pl 2012
platformadetalistow.pl 2006 -> spark.pl 2172
grupamarketer.pl 1285 -> marketerplus.pl 1743
postnord.com 1962 -> directlink.com 2262

**Comment by az** [comment]
@KarolinaTEH dzieki wielkie za company ids (przyspiesza mi to mocno sprawy)..... wszystko ogarniete oprocz grupy marketer.... w bazie widze ze nowsze ID bylo uzywane juz przez 2 poprzednie edycje (musze obadac czy to tylko repsi czy jakies inne dane tez)

**Comment by KarolinaTEH** [comment]
@az 
było (ID) -> teh25 (ID)
2322 -> 2539 (@darco.pl)
1142 -> 2442 (@iaisa.com)
1164 -> 2239 (paxy.pl)
1232 -> 2014 (linkmobility.com)
1855 -> 2012 (mbank.pl)
1493 -> 2156 (daktela.com)
1167 -> 2532 (bm.pl)
2407 -> 2022 (pirkspark.pl)
2296 -> 2527 (landmarkglobal-group.com)

**Comment by az** [comment]
fixed/updated

**Comment by az** [comment]
@KarolinaTEH linkmobility had company_id 2014 at teh24 ... shall i revert it back to 2014?

**Comment by az** [comment]
Daktela had company_id 99 at TEH23

**Comment by az** [comment]
pirkspark is a mess (2022 was used only during previous edition)

**Comment by KarolinaTEH** [comment]
pirkspark - yes, they needed a new account since their former employees had access to the previous one

**Comment by KarolinaTEH** [comment]
daktela - must have been omitted in teh23 while updating ids

**Comment by az** [comment]
so no changes
