### ISSUE TITLE
teh24 - bookingmap ticket ids excludes

### ISSUE THREAD

**Issue by az** [ecommerceberlin/targiehandlu.pl#124]
which ticket ids should be excluded on 

* top30 bookingmap
* nopTop30 bookingmap

**Comment by KarolinaTEH** [comment]
tickets to be excluded on **nonTOP30** bookingmap:
2563, 2522, //STD
2487, 2525, 2530, //HOT
2497, 2524, 2527, //SH
2506, 2523, 2531, //ULTRA
2519, 2526, 2529, //GRAND
2534, //MINI N
2510, 2513, 2538, //STAGE

tickets to be excluded on **TOP30** bookingmap:
2484, 2485, 2486, 2483, 2481, 2482, //STD
2489, 2490, 2491, 2494, 2493, 2492, 2488, //HOT
2498, 2499, 2495, 2502, 2501, 2500, 2496, //SH
2507, 2508, 2504, 2505, 2509, 2503, //ULTRA
2520, 2521, 2517, 2516, 2518, 2533 //GRAND
2512, //MINI N
2539, 2540, 2541, //STAGE
