### ISSUE TITLE
meta ads - nadanie dostępu dla agencji

### ISSUE THREAD

**Issue by KarolinaTEH** [ecommerceberlin/targiehandlu.pl#132]
**meta ads:**

Przechodzimy do ustawień firmowych:
https://business.facebook.com/settings/ad-accounts/  i wybieramy nazwę firmy, która nas interesuje.

W ustawieniach firmowych z menu po lewej stronie wybieramy zakładkę Użytkownicy -> Partnerzy -> Dodaj -> Przyznaj partnerowi dostęp do swoich zasobów.

![screen01](https://github.com/ecommerceberlin/targiehandlu.pl/assets/80756258/e7759ff9-fc29-4209-a43b-5ce9069e8d00)

Następnie w oknie, które się pojawi podajemy identyfikator konta, tj: 2616862405295410 i kolejno w oknie, które się pojawi wybieramy: Strony -> Klasyczne strony, zaznaczamy fanpage i wszystkie suwaki po prawej stronie przesuwamy w prawo.

Powtarzamy czynność dla profilu na Instagramie, konta reklamowego oraz Piksela. Na końcu klikamy Zapisz zmiany i gotowe.

![screeon03](https://github.com/ecommerceberlin/targiehandlu.pl/assets/80756258/a68f0996-fd4a-4da2-8b44-8eafe084ce1b)

**Comment by KarolinaTEH** [comment]
**linkedin ads:** 

Proszę dodać mnie do znajomych: https://www.linkedin.com/in/jakub-papuga/ a następnie w ustawieniach strony: https://www.linkedin.com/campaignmanager/accounts/ proszę wybrać z menu po lewej stronie Zarządzaj dostępem i w środkowym oknie proszę zaprosić mnie jako Menedżer Konta, wówczas ja zaproszę resztę pracowników. Proszę również o nadanie dostępu do strony na linkedin (na to samo konto).

**Comment by az** [comment]
done

**Comment by KarolinaTEH** [comment]
@az brakuje nam jeszcze dostępu do piksela. Na stronie macie zainstalowany piksel: 583926305036448 - prośba o dodanie. Robimy to tak samo jak stronę i konto reklamowe, tylko z menu po lewej stronie wybieramy zakładkę Piksele i udostępniacie go nam na id: 2616862405295410

**Comment by KarolinaTEH** [comment]
@az ping
