### ISSUE TITLE
(MAINTENANCE) 27/09 - reveal the number of votes

### ISSUE THREAD

**Issue by KarolinaTEH** [ecommerceberlin/targiehandlu.pl#139]

**Comment by az** [comment]
@KarolinaTEH PR please with show_votes={true}

**Comment by KarolinaTEH** [comment]
@az jutro rano wrzucę PR, ale dziwna sprawa, bo liczba pojawiła się już dziś, a w masterze jest:
<img width="258" alt="image" src="https://github.com/ecommerceberlin/targiehandlu.pl/assets/80756258/22496d9a-acd6-4339-ad10-b6553a5b6ed0">

**Comment by az** [comment]
@KarolinaTEH no to dziwne....jak wczoraj odblokowałem w API (bo czasami cwaniaki wyciagaly info ze zrodla danych) ... byc moze zeby bylo mniej zachodu przerobilem to tak ze jak idzie z API to pokazuje
