### ISSUE TITLE
(MAINTENANCE) OG templates update

### ISSUE THREAD

**Issue by KarolinaTEH** [ecommerceberlin/targiehandlu.pl#146]
@az linki do grafik
EXHB:
PL: https://res.cloudinary.com/eventjuicer/image/upload/v1697098261/template_teh24_exhibitor_pl.svg
EN: https://res.cloudinary.com/eventjuicer/image/upload/v1697098262/template_teh24_exhibitor_en.svg

SPKR: https://res.cloudinary.com/eventjuicer/image/upload/v1697098804/template_teh24_spkr.png

**Comment by az** [comment]
EXHs updated - https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Ftargiehandlu.pl%2Fexhibitors%2Ftkm-grouppl%3Fmeet%26utm_source%3Dexh%26utm_medium%3Dlink%26utm_campaign%3Dpromoninja%26utm_content%3Dlogotype

**Comment by az** [comment]
spkr updated
