### ISSUE TITLE
(MAINTENANCE) update settings with disables ticket ids (old, soldout)

### ISSUE THREAD

**Issue by KarolinaTEH** [ecommerceberlin/targiehandlu.pl#161]
I tried the trick of selecting 'no group' for the assigned ticket group, but it also 'unpins' the 'exhibitor' tag/role

**Comment by az** [comment]
@KarolinaTEH the best would be "disableTicketsIds" ... can you push update settings?

**Comment by KarolinaTEH** [comment]
sure
