### ISSUE TITLE
(SCHEDULE) TEH25: workshops

### ISSUE THREAD

**Issue by KarolinaTEH** [ecommerceberlin/targiehandlu.pl#164]
4-8/03 - submissions
12/03 - selection of topics
21-25/03 - attendees applications

**Comment by KarolinaTEH** [comment]
yes, translations are up to date + [PR](https://github.com/ecommerceberlin/targiehandlu.pl/pull/165)

**Comment by KarolinaTEH** [comment]
@az will you send email about submissions today/tomorrow? or KW should send info via admin? 
last year's one: https://github.com/eventjuicer/services/blob/master/resources/views/emails/company/teh24-workshops-form-pl.blade.php

**Comment by az** [comment]
@KarolinaTEH i will send.

**Comment by az** [comment]
@KarolinaTEH  mysle ze fajnie niezaleznie wyslac do prospectow-wystawcow - by bylo widac ze fajnie byc wystawcą

**Comment by az** [comment]
for the record
3/04 applications by potential participants
3-5/04 selection of participants by companies
